# Generated by Django 5.0.6 on 2024-06-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GaudeSite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='credits',
            field=models.IntegerField(default=0),
        ),
    ]
